-- Add FSRS columns to vocabulary table
ALTER TABLE vocabulary ADD COLUMN IF NOT EXISTS stability DECIMAL DEFAULT 0;
ALTER TABLE vocabulary ADD COLUMN IF NOT EXISTS fsrs_difficulty DECIMAL DEFAULT 0;
ALTER TABLE vocabulary ADD COLUMN IF NOT EXISTS fsrs_state INTEGER DEFAULT 0;
ALTER TABLE vocabulary ADD COLUMN IF NOT EXISTS reps INTEGER DEFAULT 0;
ALTER TABLE vocabulary ADD COLUMN IF NOT EXISTS lapses INTEGER DEFAULT 0;
ALTER TABLE vocabulary ADD COLUMN IF NOT EXISTS scheduled_days INTEGER DEFAULT 0;
ALTER TABLE vocabulary ADD COLUMN IF NOT EXISTS elapsed_days INTEGER DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_vocabulary_fsrs_state ON vocabulary(fsrs_state);
